Q3) In a financial forecasting scenario, provided a dataset with columns for Date, Revenue, and Expenses, how would you use pandas pivot tables to analyze the monthly cash flow trends by summarizing revenues and expenses?

In [ ]:
import pandas as pd
from datetime import datetime, timedelta
import numpy as np

# Generate sample data
np.random.seed(0)

# Generate dates for the past year
start_date = datetime(2023, 1, 1)
end_date = datetime(2023, 12, 31)
dates = pd.date_range(start=start_date, end=end_date, freq='D')

# Generate random revenues and expenses
revenues = np.random.randint(10000, 50000, size=len(dates))
expenses = np.random.randint(5000, 30000, size=len(dates))

# Create DataFrame
data = {
    'Date': dates,
    'Revenue': revenues,
    'Expenses': expenses
}
df = pd.DataFrame(data)

# Save DataFrame to CSV
df.to_csv('financial_data.csv', index=False)

In [ ]:
# Read the CSV file into a DataFrame
df = pd.read_csv('financial_data.csv')

In [ ]:
# Convert 'Date' column to datetime type
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
# Set 'Date' column as the index
df.set_index('Date', inplace=True)

In [ ]:

# Create pivot table to analyze monthly cash flow trends
pivot_table = pd.pivot_table(df, index=df.index.to_period('M'), values=['Revenue', 'Expenses'],
                             aggfunc='sum')

In [ ]:

# Add a column for Cash Flow (Revenue - Expenses)
pivot_table['Cash Flow'] = pivot_table['Revenue'] - pivot_table['Expenses']

In [ ]:
# Display the pivot table
print(pivot_table)

         Expenses  Revenue  Cash Flow
Date
2023-01    547164   933026     385862
2023-02    516907   804278     287371
2023-03    528708   876044     347336
2023-04    447863  1011713     563850
2023-05    523110   859463     336353
2023-06    560457   867412     306955
2023-07    592682   853103     260421
2023-08    508857  1012214     503357
2023-09    492092   925660     433568
2023-10    450477  1003830     553353
2023-11    546145   836460     290315
2023-12    520541   946061     425520